spring:
  kafka:
    listener:
      observation-enabled: true
    template:
      observation-enabled: true
  application:
    name: config-service
  config:
    import: "optional:file:../Deployment/config-service.yml"
  cloud:
    config:
      server:
        native:
          search-locations: file:../Deployment/
  security:
    user:
      name: ${CONFIG_USER:admin}
      password: ${CONFIG_PASSWORD:admin}
  profiles:
    active: native

logging:
  file:
    name: logs/${spring.application.name}.log
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] [%t] %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 1GB


management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
